{
 "title": "Concordium Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Baker ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "concordium_baker_id" }
   ]
  },
  {
   "title": "Baker Status",
   "type": "stat",
   "description": "1 = STATUS OF BAKER IS TRUE",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "concordium_baker_running" }
   ]
  },
  {
   "title": "finalization period EMA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "concordium_finalization_period_inEMA"
    }
   ]
  },
  {
   "title": "packet amount[5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(concordium_peer_total_received_amount[5m])",
     "legendFormat": "received packet"
    },
    {
     "expr": "rate(concordium_peer_total_sent_amount[5m])",
     "legendFormat": "sent packet"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    { "expr": "concordium_best_block_height", "legendFormat": "best_block_height" },
    {
     "expr": "concordium_last_finalized_block_height",
     "legendFormat": "last_finalized_height"
    }
   ]
  },
  {
   "title": "Finalized block",
   "type": "timeseries",
   "description": "Finalized block count after this node started.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "targets": [
    { "expr": "concordium_finalization_count" }
   ]
  },
  {
   "title": "Period of block arriving/receiving",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "concordium_block_arrive_period_inEMA",
     "legendFormat": "Arriving period"
    },
    {
     "expr": "concordium_block_receive_period_inEMA",
     "legendFormat": "Receiving period"
    }
   ]
  },
  {
   "title": "Transaction per block EMA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "concordium_transactions_per_block_inEMA"
    }
   ]
  },
  {
   "title": "Difference with finalized/unfinalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "concordium_best_block_height - concordium_last_finalized_block_height"
    }
   ]
  },
  {
   "title": "Received Block latency EMA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "concordium_block_receive_latency_inEMA",
     "legendFormat": "received block latency"
    },
    {
     "expr": "concordium_block_arrive_latency_inEMA",
     "legendFormat": "arrived block latency"
    }
   ]
  }
 ]
}